"""Day 1: channel envelopes and Google Calendar integration."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="a1d2e3f4b5c6"; down_revision="9c7e6d5a4b21"; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("calendar_connections",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("business_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("connected_by",postgresql.UUID(as_uuid=True)),sa.Column("provider",sa.String(30),nullable=False,server_default="GOOGLE"),sa.Column("calendar_id",sa.String(500),nullable=False,server_default="primary"),sa.Column("account_email",sa.String(255)),sa.Column("access_token_encrypted",sa.Text(),nullable=False),sa.Column("refresh_token_encrypted",sa.Text()),sa.Column("token_expires_at",sa.DateTime(timezone=True)),sa.Column("scope",sa.Text()),sa.Column("metadata_json",postgresql.JSONB(astext_type=sa.Text())),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.ForeignKeyConstraint(["business_id"],["businesses.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["connected_by"],["users.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("business_id"))
    op.create_index("ix_calendar_connections_business_id","calendar_connections",["business_id"])
    op.create_table("channel_messages",sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("business_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("conversation_id",postgresql.UUID(as_uuid=True)),sa.Column("channel",sa.String(30),nullable=False),sa.Column("direction",sa.String(20),nullable=False),sa.Column("external_user_id",sa.String(255)),sa.Column("external_message_id",sa.String(255)),sa.Column("provider_message_id",sa.String(255)),sa.Column("message",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="RECEIVED"),sa.Column("metadata_json",postgresql.JSONB(astext_type=sa.Text())),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.ForeignKeyConstraint(["business_id"],["businesses.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["conversation_id"],["conversations.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("business_id","channel","external_message_id",name="uq_channel_messages_external_id"))
    op.create_index("ix_channel_messages_business_id","channel_messages",["business_id"]); op.create_index("ix_channel_messages_conversation_id","channel_messages",["conversation_id"]); op.create_index("ix_channel_messages_business_channel","channel_messages",["business_id","channel"])
    op.add_column("appointments",sa.Column("calendar_provider",sa.String(30))); op.add_column("appointments",sa.Column("calendar_event_id",sa.String(500))); op.add_column("appointments",sa.Column("calendar_html_link",sa.String(1000)))
def downgrade():
    op.drop_column("appointments","calendar_html_link"); op.drop_column("appointments","calendar_event_id"); op.drop_column("appointments","calendar_provider")
    op.drop_index("ix_channel_messages_business_channel",table_name="channel_messages"); op.drop_index("ix_channel_messages_conversation_id",table_name="channel_messages"); op.drop_index("ix_channel_messages_business_id",table_name="channel_messages"); op.drop_table("channel_messages")
    op.drop_index("ix_calendar_connections_business_id",table_name="calendar_connections"); op.drop_table("calendar_connections")
